name: Build and test

on:
  pull_request:

jobs:
  build:

    name: Build and test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add NuGet Source
      run: dotnet nuget add source --username ArknightsResources --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ArknightsResources/index.json"

    - name: Install dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test
